project_name: polygon-edge

release:
  disable: false
  draft: true
  prerelease: auto

builds:
  - id: linux-amd64
    main: ./main.go
    binary: polygon-edge
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    ldflags:
      # We need to build a static binary because we are building in a glibc based system and running in a musl container
      -s -w -extldflags "-static" -X 'github.com/0xPolygon/polygon-edge/versioning.Version=v{{ .Version }}'
    tags:
      - netgo

archives:
  -
    files:
      - LICENSE
      - README.md

#nfpms:
#  - vendor: 0xPolygon
#    homepage: https://polygon.technology
#    maintainer: Polygon Edge Team <edge@polygon.technology>
#    description:  A Framework for Building Ethereum-compatible Blockchain Networks
#    license: GPLv3 LGPLv3
#
#    formats:
#      - apk
#      - deb
#      - rpm
#
#    contents:
#      - src: polygon-edge.service
#        dst: /lib/systemd/system/polygon-edge.service
#        type: config
#
#    overrides:
#      rpm:
#        replacements:
#          amd64: x86_64

snapshot:
  name_template: "{{ .Tag }}.next"

